/// Second dark theme. Warmer and higher contrast than Pocket Dark — easier in
/// bright ambient light, where cool blue-greys wash out.
library;

import 'package:flutter/material.dart';
import 'package:pocket_code/core/theme/editor_color_theme.dart';

const EditorColorTheme emberDarkEditorTheme = EditorColorTheme(
  id: 'ember-dark',
  name: 'Ember',
  isDark: true,
  background: Color(0xFF1A1614),
  foreground: Color(0xFFEDE4D8),
  gutterBackground: Color(0xFF1A1614),
  gutterText: Color(0xFF6B5D50),
  gutterActiveText: Color(0xFFD4C4B0),
  currentLine: Color(0xFF241E1A),
  selection: Color(0xFF5A3E22),
  cursor: Color(0xFFFF9E3D),
  bracketMatch: Color(0xFF8A7560),
  findMatch: Color(0xFF4A4420),
  findMatchActive: Color(0xFF7A5C18),
  indentGuide: Color(0xFF302822),
  whitespace: Color(0xFF423730),
  syntax: <String, TextStyle>{
    'root': TextStyle(color: Color(0xFFEDE4D8)),
    'keyword': TextStyle(color: Color(0xFFFF8A5C)),
    'built_in': TextStyle(color: Color(0xFF7FC4A8)),
    'type': TextStyle(color: Color(0xFFF0C674)),
    'literal': TextStyle(color: Color(0xFFE8A33D)),
    'number': TextStyle(color: Color(0xFFE8A33D)),
    'string': TextStyle(color: Color(0xFFB5BD68)),
    'regexp': TextStyle(color: Color(0xFF7FC4A8)),
    'subst': TextStyle(color: Color(0xFFEDE4D8)),
    'symbol': TextStyle(color: Color(0xFFE8A33D)),
    'class': TextStyle(color: Color(0xFFF0C674)),
    'title': TextStyle(color: Color(0xFFFFC66D)),
    'class-title': TextStyle(color: Color(0xFFF0C674)),
    'function': TextStyle(color: Color(0xFFFFC66D)),
    'params': TextStyle(color: Color(0xFFEDE4D8)),
    'comment': TextStyle(color: Color(0xFF7A6A5C), fontStyle: FontStyle.italic),
    'doctag': TextStyle(color: Color(0xFF9A8A6C), fontStyle: FontStyle.italic),
    'meta': TextStyle(color: Color(0xFF9A8878)),
    'meta-keyword': TextStyle(color: Color(0xFFFF8A5C)),
    'meta-string': TextStyle(color: Color(0xFFB5BD68)),
    'variable': TextStyle(color: Color(0xFFE8858B)),
    'template-variable': TextStyle(color: Color(0xFFE8858B)),
    'attr': TextStyle(color: Color(0xFFE8A33D)),
    'attribute': TextStyle(color: Color(0xFFE8A33D)),
    'name': TextStyle(color: Color(0xFFE8858B)),
    'section': TextStyle(color: Color(0xFFFFC66D)),
    'tag': TextStyle(color: Color(0xFFE8858B)),
    'selector-tag': TextStyle(color: Color(0xFFE8858B)),
    'selector-id': TextStyle(color: Color(0xFFFFC66D)),
    'selector-class': TextStyle(color: Color(0xFFF0C674)),
    'selector-attr': TextStyle(color: Color(0xFFFF8A5C)),
    'selector-pseudo': TextStyle(color: Color(0xFF7FC4A8)),
    'bullet': TextStyle(color: Color(0xFF7FC4A8)),
    'quote': TextStyle(color: Color(0xFF7A6A5C), fontStyle: FontStyle.italic),
    'link': TextStyle(color: Color(0xFF7FC4A8), decoration: TextDecoration.underline),
    'formula': TextStyle(color: Color(0xFFFF8A5C)),
    'emphasis': TextStyle(fontStyle: FontStyle.italic),
    'strong': TextStyle(fontWeight: FontWeight.bold),
    'addition': TextStyle(color: Color(0xFFB5BD68)),
    'deletion': TextStyle(color: Color(0xFFE8858B)),
  },
);
