/// Light editor theme. Tuned for outdoor and high-glare use: strong foreground
/// contrast, saturated syntax colours that survive screen dimming.
library;

import 'package:flutter/material.dart';
import 'package:pocket_code/core/theme/editor_color_theme.dart';

const EditorColorTheme pocketLightEditorTheme = EditorColorTheme(
  id: 'pocket-light',
  name: 'Pocket Light',
  isDark: false,
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF1F2328),
  gutterBackground: Color(0xFFFFFFFF),
  gutterText: Color(0xFF9AA1AB),
  gutterActiveText: Color(0xFF1F2328),
  currentLine: Color(0xFFF2F5F9),
  selection: Color(0xFFBFD9F7),
  cursor: Color(0xFF0B62D0),
  bracketMatch: Color(0xFF9AA1AB),
  findMatch: Color(0xFFFFF0A8),
  findMatchActive: Color(0xFFFFC96B),
  indentGuide: Color(0xFFE4E7EC),
  whitespace: Color(0xFFCBD1D9),
  syntax: <String, TextStyle>{
    'root': TextStyle(color: Color(0xFF1F2328)),
    'keyword': TextStyle(color: Color(0xFF9A29A8)),
    'built_in': TextStyle(color: Color(0xFF0A7C8C)),
    'type': TextStyle(color: Color(0xFF8A5B00)),
    'literal': TextStyle(color: Color(0xFFB2512C)),
    'number': TextStyle(color: Color(0xFFB2512C)),
    'string': TextStyle(color: Color(0xFF1A7F37)),
    'regexp': TextStyle(color: Color(0xFF0A7C8C)),
    'subst': TextStyle(color: Color(0xFF1F2328)),
    'symbol': TextStyle(color: Color(0xFFB2512C)),
    'class': TextStyle(color: Color(0xFF8A5B00)),
    'title': TextStyle(color: Color(0xFF0B62D0)),
    'class-title': TextStyle(color: Color(0xFF8A5B00)),
    'function': TextStyle(color: Color(0xFF0B62D0)),
    'params': TextStyle(color: Color(0xFF1F2328)),
    'comment': TextStyle(color: Color(0xFF6E7781), fontStyle: FontStyle.italic),
    'doctag': TextStyle(color: Color(0xFF4A7A4E), fontStyle: FontStyle.italic),
    'meta': TextStyle(color: Color(0xFF6E7781)),
    'meta-keyword': TextStyle(color: Color(0xFF9A29A8)),
    'meta-string': TextStyle(color: Color(0xFF1A7F37)),
    'variable': TextStyle(color: Color(0xFFC0293B)),
    'template-variable': TextStyle(color: Color(0xFFC0293B)),
    'attr': TextStyle(color: Color(0xFFB2512C)),
    'attribute': TextStyle(color: Color(0xFFB2512C)),
    'name': TextStyle(color: Color(0xFFC0293B)),
    'section': TextStyle(color: Color(0xFF0B62D0)),
    'tag': TextStyle(color: Color(0xFFC0293B)),
    'selector-tag': TextStyle(color: Color(0xFFC0293B)),
    'selector-id': TextStyle(color: Color(0xFF0B62D0)),
    'selector-class': TextStyle(color: Color(0xFF8A5B00)),
    'selector-attr': TextStyle(color: Color(0xFF9A29A8)),
    'selector-pseudo': TextStyle(color: Color(0xFF0A7C8C)),
    'bullet': TextStyle(color: Color(0xFF0A7C8C)),
    'quote': TextStyle(color: Color(0xFF6E7781), fontStyle: FontStyle.italic),
    'link': TextStyle(color: Color(0xFF0A7C8C), decoration: TextDecoration.underline),
    'formula': TextStyle(color: Color(0xFF9A29A8)),
    'emphasis': TextStyle(fontStyle: FontStyle.italic),
    'strong': TextStyle(fontWeight: FontWeight.bold),
    'addition': TextStyle(color: Color(0xFF1A7F37)),
    'deletion': TextStyle(color: Color(0xFFC0293B)),
  },
);
