/// Default editor theme. Balanced, low-fatigue, familiar to anyone who has used
/// a One Dark derivative — deliberately unsurprising for the default.
library;

import 'package:flutter/material.dart';
import 'package:pocket_code/core/theme/editor_color_theme.dart';

const EditorColorTheme pocketDarkEditorTheme = EditorColorTheme(
  id: 'pocket-dark',
  name: 'Pocket Dark',
  isDark: true,
  background: Color(0xFF12141A),
  foreground: Color(0xFFD7DCE5),
  gutterBackground: Color(0xFF12141A),
  gutterText: Color(0xFF4A5163),
  gutterActiveText: Color(0xFFAEB6C4),
  currentLine: Color(0xFF1A1D25),
  selection: Color(0xFF2A4A6B),
  cursor: Color(0xFF4D9FFF),
  bracketMatch: Color(0xFF5C6B80),
  findMatch: Color(0xFF3A4A28),
  findMatchActive: Color(0xFF6B5A1E),
  indentGuide: Color(0xFF262A33),
  whitespace: Color(0xFF333947),
  syntax: <String, TextStyle>{
    'root': TextStyle(color: Color(0xFFD7DCE5)),
    'keyword': TextStyle(color: Color(0xFFC792EA)),
    'built_in': TextStyle(color: Color(0xFF56B6C2)),
    'type': TextStyle(color: Color(0xFFE5C07B)),
    'literal': TextStyle(color: Color(0xFFD19A66)),
    'number': TextStyle(color: Color(0xFFD19A66)),
    'string': TextStyle(color: Color(0xFF98C379)),
    'regexp': TextStyle(color: Color(0xFF56B6C2)),
    'subst': TextStyle(color: Color(0xFFD7DCE5)),
    'symbol': TextStyle(color: Color(0xFFD19A66)),
    'class': TextStyle(color: Color(0xFFE5C07B)),
    'title': TextStyle(color: Color(0xFF61AFEF)),
    'class-title': TextStyle(color: Color(0xFFE5C07B)),
    'function': TextStyle(color: Color(0xFF61AFEF)),
    'params': TextStyle(color: Color(0xFFD7DCE5)),
    'comment': TextStyle(color: Color(0xFF5C6370), fontStyle: FontStyle.italic),
    'doctag': TextStyle(color: Color(0xFF7F9E6C), fontStyle: FontStyle.italic),
    'meta': TextStyle(color: Color(0xFF7F848E)),
    'meta-keyword': TextStyle(color: Color(0xFFC792EA)),
    'meta-string': TextStyle(color: Color(0xFF98C379)),
    'variable': TextStyle(color: Color(0xFFE06C75)),
    'template-variable': TextStyle(color: Color(0xFFE06C75)),
    'attr': TextStyle(color: Color(0xFFD19A66)),
    'attribute': TextStyle(color: Color(0xFFD19A66)),
    'name': TextStyle(color: Color(0xFFE06C75)),
    'section': TextStyle(color: Color(0xFF61AFEF)),
    'tag': TextStyle(color: Color(0xFFE06C75)),
    'selector-tag': TextStyle(color: Color(0xFFE06C75)),
    'selector-id': TextStyle(color: Color(0xFF61AFEF)),
    'selector-class': TextStyle(color: Color(0xFFE5C07B)),
    'selector-attr': TextStyle(color: Color(0xFFC792EA)),
    'selector-pseudo': TextStyle(color: Color(0xFF56B6C2)),
    'bullet': TextStyle(color: Color(0xFF56B6C2)),
    'quote': TextStyle(color: Color(0xFF5C6370), fontStyle: FontStyle.italic),
    'link': TextStyle(color: Color(0xFF56B6C2), decoration: TextDecoration.underline),
    'formula': TextStyle(color: Color(0xFFC792EA)),
    'emphasis': TextStyle(fontStyle: FontStyle.italic),
    'strong': TextStyle(fontWeight: FontWeight.bold),
    'addition': TextStyle(color: Color(0xFF98C379)),
    'deletion': TextStyle(color: Color(0xFFE06C75)),
  },
);
